ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "DevM";
GRANT USAGE, CREATE ON SCHEMA public TO "DevM";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "DevM";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "DevM";