"""Add live meeting fields to transcript model

Revision ID: dd962e67b7fc
Revises: 
Create Date: 2026-04-24 19:33:09.526527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd962e67b7fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('summaries_meeting_id_key'), 'summaries', type_='unique')
    op.create_index(op.f('ix_summaries_created_at'), 'summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_summaries_meeting_id'), 'summaries', ['meeting_id'], unique=False)
    op.add_column('transcripts', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('transcripts', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('transcripts', sa.Column('is_final', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'is_final')
    op.drop_column('transcripts', 'language')
    op.drop_column('transcripts', 'confidence')
    op.drop_index(op.f('ix_summaries_meeting_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_created_at'), table_name='summaries')
    op.create_unique_constraint(op.f('summaries_meeting_id_key'), 'summaries', ['meeting_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
