"""Add structured insights fields to summary model

Revision ID: ea3b3c0e2349
Revises: dd962e67b7fc
Create Date: 2026-04-24 19:41:41.285325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3b3c0e2349'
down_revision: Union[str, Sequence[str], None] = 'dd962e67b7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('decisions', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('risks', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('next_steps', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('topics', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('meeting_analytics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'meeting_analytics')
    op.drop_column('summaries', 'topics')
    op.drop_column('summaries', 'next_steps')
    op.drop_column('summaries', 'risks')
    op.drop_column('summaries', 'decisions')
    # ### end Alembic commands ###
